<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>North Crafts</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="http://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="..view/css.css">
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <a class="navbar-brand" href=" ">North Crafts</a>
        <ul class="nav navbar-nav navbar-right">
            <li><a href="/admin">Admin</a></li>
        </ul>
    </div>
</nav>

<?php echo $content ?> 

</body>
</html>